# configuration for "master" branch
- 
  branches:
    only:
      - master
  image: Visual Studio 2017
  platform: Any CPU
  configuration: Release
  install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  build_script:
  - ps: ./build.ps1 Build
  - ps: ./build.ps1 CreateNuget
  test_script:
  - ps: ./build.ps1 RunTests
  artifacts:
  - path: build/nuget/*.nupkg
    name: nuget
  deploy:
    provider: NuGet
    api_key:
      secure: MDy+BPQGSr14yFXozwVy+08y1RbLv35gL9I/5Ao5nLfYrnj7zX+cJLXfeb8ajyHh
    skip_symbols: false
    artifact: /.*\.nupkg/

# configuration for all branches starting from "dev"
- 
  branches:
    only:
      - dev
  image: Visual Studio 2017
  platform: Any CPU
  configuration: Release
  install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  build_script:
  - ps: ./build.ps1 Build
  - ps: ./build.ps1 CreateNuget
  test_script:
  - ps: ./build.ps1 RunTests
  artifacts:
  - path: build/nuget/*.nupkg
    name: nuget
  deploy:
    provider: NuGet
    server: https://www.myget.org/F/akkadotnet-contrib/api/v2/package
    api_key:
      secure: yoMgcchmDuXbvT90bgrUTOUNYgAId6QI0nofIOtnlfWzMjDEWfOqNqqTGPY+02M+
    skip_symbols: false
    symbol_server: https://www.myget.org/F/akkadotnet-contrib/symbols/api/v2/package
    artifact: /.*\.nupkg/
